version: 2
aliases:
    - &save-yarn-deps
      name: Save Yarn Package Cache
      key: v1-yarn-packages-{{ checksum "yarn.lock" }}
      paths:
          - ~/.yarn-cache
    - &restore-yarn-deps
      name: Restore Yarn Package Cache
      keys:
          - v1-yarn-packages-{{ checksum "yarn.lock" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-yarn-packages-
    - &install-yarn-deps
      name: "Lint"
      command: yarn lint:pkg
jobs:
    build:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: *restore-yarn-deps
            - run: *install-yarn-deps
            - save_cache: *save-yarn-deps
            - run:
                  name: "Lint"
                  command: yarn lint:pkg
    chromatic:
        docker:
            - image: circleci/node:12
        steps:
            - checkout
            - restore_cache: *restore-yarn-deps
            - run: *install-yarn-deps
            - save_cache: *save-yarn-deps
            - run:
                  name: "Chromatic"
                  command: yarn chromatic:ci
workflows:
    version: 2
    commit:
        jobs:
            - build
            - chromatic:
                  filters:
                      branches:
                          only:
                              - master
